name: BUILD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Build for production
      run: npm run build
    - uses: actions/upload-artifact@v3
      with:
        path: |
          app
          bootstrap
          config
          database
          public
          resources/views
          routes
          storage
          composer.{json,lock}
          artisan
