name: BUILD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Build for production
      run: npm run build
    - name: Build artifact
      run: |
        mkdir build
        rm -rf resources/css resources/js
        cp -r app bootstrap config database public resources routes storage composer* artisan build
        cd build
        tar -czvf build.tar.gz .
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/build.tar.gz
